[package]
name = "day06"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmaps = "3.1.0"
nom = "7.1.0"

[dev-dependencies]
pretty_assertions = "1.0.0"
